- 1.1.5
- _NAME: G613 Wireless Mechanical Gaming Keyboard
  _absent: [hi-res-scroll, lowres-scroll-mode, hires-smooth-invert, hires-smooth-resolution, hires-scroll-mode, smart-shift, thumb-scroll-invert, thumb-scroll-mode,
    onboard_profiles, pointer_speed, dpi, speed-change, backlight, backlight-timed, fn-swap, reprogrammable-keys, persistent-remappable-keys, disable-keyboard-keys,
    crown-smooth, divert-crown, m-key-leds, mr-key-led, multiplatform, gesture2-gestures, gesture2-divert, gesture2-params, sidetone, equalizer]
  _battery: 4096
  _modelId: B34F40650000
  _serial: C81DA1E2
  _unitId: 52D8838E
  _wpid: '4065'
  change-host: null
  divert-gkeys: false
  divert-keys: {209: 0, 210: 0}
  report_rate: 1
- _NAME: G603 Wireless Gaming Mouse
  _absent: [hi-res-scroll, lowres-scroll-mode, hires-smooth-invert, hires-smooth-resolution, hires-scroll-mode, smart-shift, thumb-scroll-invert, thumb-scroll-mode,
    report_rate, pointer_speed, speed-change, backlight, backlight-timed, fn-swap, reprogrammable-keys, persistent-remappable-keys, disable-keyboard-keys,
    crown-smooth, divert-crown, divert-gkeys, m-key-leds, mr-key-led, multiplatform, gesture2-gestures, gesture2-divert, gesture2-params, sidetone, equalizer]
  _battery: 4096
  _modelId: B01C406C0000
  _sensitive: {divert-keys: false}
  _serial: 214852B5
  _unitId: 68F474DA
  _wpid: 406C
  change-host: null
  divert-keys: {209: 0, 210: 0}
  dpi: 800
  onboard_profiles: 1
