source ~/.local/share/popfury/defaults/bash/rc

# Editor used by CLI
export EDITOR="nano"
export SUDO_EDITOR="nano"

# Initialize Starship prompt
eval "$(starship init bash)"

# Might be needed for Lutris to run
export PATH=$PATH:/usr/games